spring:
  application :
    name: store-integration-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/usecase
    
    username: root
    
    password: admin
    
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
server:
  port: 8003 
       
   