spring:
  application :
    name: store-details-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/usecase
    
    username: root
    
    password: root
    
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
server:
  port: 8003
   
store-integration-service:
  ribbon:
    listOfServers: http://localhost:8004,http://localhost:8005
    
    
    
    
     
   