spring:
  application :
    name: store-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/usecase
    
    username: root
    
    password: root
    
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update  cloud:    config:      server:        git:          uri: ${HOME}/UseCaseGit/SoreIntegration      uri:      - http://localhost:8001
        
server:
  port: 8001
  
my:
  path: C:\Users\jagad\OneDrive\Desktop\MiniProject\Json
  

  
#  pont.email.template.location=classpath:templates/mailTemplate.html
  

#management:#  endpoints:#    web:#      exposure:#        include: "*"       
#   